ROOT: 'output/snakemake'
ANNOTATIONS: 'annotations'
py_env : mubind
timing: false

HYPERPARAM:
    n_epochs: [10, 20, 30]
    batch_sizes: [32, 64, 128]
    learning_rates: [0.001, 0.01, 0.1]
    n_kernels: [1, 2, 3, 4, 5, 6]
    w: 15
    early_stopping: 100
    n_sample: 1000

EXPERIMENT:
  SELEX:
    count_data: True

  PBM:
    count_data: False

