ROOT: 'output/snakemake_test'
ANNOTATIONS: 'annotations'
py_env : mubind
timing: false

HYPERPARAM:
    n_epochs: [2]
    batch_sizes: [64]
    learning_rates: [0.1]
    n_kernels: [5]
    width: 15
    early_stopping: 100
    n_sample: [50,] # 1000
    use_mono: True
    use_dinuc: False
    dinuc_mode: local
    seq_bias: True

EXPERIMENT:
  SELEX:
    count_data: True
  PBM:
    count_data: False

