ROOT: 'output/snakemake_test'
ANNOTATIONS: 'annotations'
py_env : multibind
timing: false

HYPERPARAM:
    n_epochs: [2]
    batch_sizes: [64]
    learning_rates: [0.01]
    n_kernels: [2]
    w: 15
    early_stopping: 100
    n_sample: 100

EXPERIMENT:
  SELEX:
    count_data: True
  # PBM:
  #   count_data: False

